use_frameworks!

def shared_pods
pod 'FRadioPlayer'
pod 'CollectionViewSlantedLayout', '~> 3.1'
pod 'LGButton'
pod 'PromiseKit'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
end

target 'hackaton' do
     shared_pods
end
